using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Kabomu.QuasiHttp.EntityBody
{
    /// <summary>
    /// Exception thrown when an imposed limit on the size of a quasi http body is exceeded during reading.
    /// </summary>
    public class BodySizeLimitExceededException : QuasiHttpException
    {
        /// <summary>
        /// Creates new instance.
        /// </summary>
        /// <param name="bodySizeLimit">the maximum size limit allowed for request body</param>
        public BodySizeLimitExceededException(int bodySizeLimit) : this(bodySizeLimit, null, null)
        {
        }

        /// <summary>
        /// Creates new instance with a possible custom message and underlying cause of the exception.
        /// </summary>
        /// <param name="bodySizeLimit">the maximum size limit allowed for request body</param>
        /// <param name="message">error message or null to create a default message based on body size limit</param>
        /// <param name="innerException">any underlying cause of this exception</param>
        public BodySizeLimitExceededException(int bodySizeLimit, string message, Exception innerException) :
            base(message ?? CreateErrorMessage(bodySizeLimit), innerException)
        {
            BodySizeLimit = bodySizeLimit;
        }

        /// <summary>
        /// Gets the body size limit leading to this exception.
        /// </summary>
        public int BodySizeLimit { get; }

        /// <summary>
        /// Creates default error message. This function is the one called when a null message argument is
        /// supplied to constructors of this class. It is exposed publicly for the purpose of prepending or appending to
        /// the message generated by this function.
        /// </summary>
        /// <param name="bodySizeLimit">maximum body size limit to include in error message</param>
        /// <returns>default error message describing maximum body size.</returns>
        public static string CreateErrorMessage(int bodySizeLimit)
        {
            return $"body size limit of {bodySizeLimit} bytes exceeded";
        }
    }
}
