using System;
using System.Collections.Generic;
using System.Text;

namespace Kabomu.QuasiHttp.EntityBody
{
    /// <summary>
    /// Exception thrown when the reading of a quasi http body ends and the total number of bytes read is less than
    /// its content length value.
    /// </summary>
    public class ContentLengthNotSatisfiedException : QuasiHttpException
    {
        /// <summary>
        /// Creates new instance with a default error message.
        /// </summary>
        /// <param name="contentLength">the content length value which could not be satisfied.</param>
        public ContentLengthNotSatisfiedException(long contentLength) : this(contentLength, null, null)
        {
        }

        /// <summary>
        /// Creates new instance with a possible custom message and underlying cause of the exception.
        /// </summary>
        /// <param name="contentLength">the content length value which could not be satisfied.</param>
        /// <param name="message">error message or null to create a default message based on content length</param>
        /// <param name="innerException">any underlying cause of this exception</param>
        public ContentLengthNotSatisfiedException(long contentLength, string message, Exception innerException) :
            base(message ?? CreateErrorMessage(contentLength), innerException)
        {
            ContentLength = contentLength;
        }

        /// <summary>
        /// Gets the content length leading to this exception.
        /// </summary>
        public long ContentLength { get; }

        /// <summary>
        /// Creates default error message. This function is the one called when a null message argument is
        /// supplied to constructors of this class. It is exposed publicly for the purpose of prepending or appending to
        /// the message generated by this function.
        /// </summary>
        /// <param name="contentLength">content length to include in error message</param>
        /// <returns>default error message describing content length.</returns>
        public static string CreateErrorMessage(long contentLength)
        {
            return $"insufficient bytes available to satisfy content length of {contentLength} bytes";
        }
    }
}
